/**
 * **每會話模型選擇走完產品路徑**——[#723](https://github.com/DemianLi/nexus-agent/issues/723) 的驗收。機制本身的規則在
 * `packages/nexus-core/src/model-selection.test.ts`。
 *
 * 組裝走 `createCliAgent({ live: true })` 與出貨清單，模型是真的 `ChatOpenAI`，對手方是本機的假 Chat Completions 端點，
 * 所以量到的是**真的會送上線的請求本體**：換了模型 `model` 欄位是哪一個、通知在不在、沒選過的會話送出去的東西有沒有變。
 *
 * **零憑證、零外部連線。**
 */

import { createServer } from 'node:http';
import type { AddressInfo } from 'node:net';
import type { SessionEvent } from '@nexus/core';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { createCliAgent } from './assembly-root.js';
import { shippedPlugins } from './fixtures.js';
import { DEFAULT_LIVE_MODEL_ENTRY, LIVE_API_KEY_ENV } from './live-model.js';
import { foldModelSelection, modelSelectionView } from './model-selection-host.js';
import { liveModelConfigSchema } from './settings/live-model.js';
import { ThreadPump } from './thread-pump.js';
import type { PumpAgent } from './thread-pump.js';

const shipped = await shippedPlugins();

const A = 'model-a';
const B = 'model-b';

const NOTICE_A_TO_B = `[model changed: assistant turns above this point were generated by ${A}; the session continues with ${B}]`;

interface WireRequest {
  readonly model: string;
  readonly messages: readonly { readonly role: string; readonly content: unknown }[];
  readonly body: Record<string, unknown>;
}

/** 照腳本回答（一律走 SSE）的假端點。`onRequest` 在第 n 次請求到達時呼叫，給「這一步跑到一半才選」用。 */
async function fakeEndpoint(
  replies: readonly { text?: string; call?: { id: string; name: string; arguments: string } }[],
  onRequest?: (count: number) => void,
) {
  const requests: WireRequest[] = [];
  const server = createServer((req, res) => {
    let raw = '';
    req.on('data', (chunk: Buffer) => (raw += chunk.toString()));
    req.on('end', () => {
      const body = JSON.parse(raw) as Record<string, unknown>;
      requests.push({
        model: String(body.model),
        messages: (body.messages ?? []) as WireRequest['messages'],
        body,
      });
      onRequest?.(requests.length);
      const reply = replies[requests.length - 1] ?? { text: '好。' };
      const chunk = (
        delta: Record<string, unknown>,
        finish: string | null = null,
        usage?: unknown,
      ) =>
        `data: ${JSON.stringify({
          id: `chatcmpl-${requests.length}`,
          object: 'chat.completion.chunk',
          created: 0,
          model: 'fake',
          choices: [{ index: 0, delta, finish_reason: finish }],
          ...(usage !== undefined && { usage }),
        })}\n\n`;
      res.writeHead(200, { 'content-type': 'text/event-stream' });
      res.write(chunk({ role: 'assistant', content: reply.text ?? '' }));
      if (reply.call !== undefined) {
        res.write(
          chunk({
            tool_calls: [
              {
                index: 0,
                id: reply.call.id,
                type: 'function',
                function: { name: reply.call.name, arguments: reply.call.arguments },
              },
            ],
          }),
        );
      }
      res.write(chunk({}, reply.call === undefined ? 'stop' : 'tool_calls'));
      res.write(
        `data: ${JSON.stringify({
          id: `chatcmpl-${requests.length}`,
          object: 'chat.completion.chunk',
          created: 0,
          model: 'fake',
          choices: [],
          usage: { prompt_tokens: 10, completion_tokens: 2, total_tokens: 12 },
        })}\n\n`,
      );
      res.end('data: [DONE]\n\n');
    });
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', () => resolve()));
  const { port } = server.address() as AddressInfo;
  return {
    baseUrl: `http://127.0.0.1:${port}/v1`,
    requests,
    close: async () => {
      server.closeAllConnections();
      await new Promise<void>((resolve) => server.close(() => resolve()));
    },
  };
}

let savedKey: string | undefined;
beforeEach(() => {
  savedKey = process.env[LIVE_API_KEY_ENV];
  process.env[LIVE_API_KEY_ENV] = 'fake-key-for-loopback';
});
afterEach(() => {
  if (savedKey === undefined) delete process.env[LIVE_API_KEY_ENV];
  else process.env[LIVE_API_KEY_ENV] = savedKey;
});

/** 兩顆：A 預設（宣告 `off`）、B 窗口小且沒有推理資訊。 */
function configFor(baseUrl: string) {
  const entry = (id: string, extra: Record<string, unknown> = {}) => ({
    ...structuredClone(DEFAULT_LIVE_MODEL_ENTRY),
    id,
    ...extra,
  });
  return liveModelConfigSchema.parse({
    baseUrl,
    maxRetries: 0,
    modelId: A,
    models: [
      entry(A),
      entry(B, { contextWindow: 65_000, maxTokens: 4_000, reasoningEfforts: false }),
    ],
  });
}

async function assemble(baseUrl: string) {
  const built = await createCliAgent(
    { live: true, liveModel: configFor(baseUrl) },
    shipped,
    undefined,
    {},
  );
  const pump = new ThreadPump(built.agent as unknown as PumpAgent, 'model-selection');
  const detach = built.attachSessions(pump.sessions);
  const host = built.modelSelection!;
  return {
    built,
    pump,
    host,
    log: pump.sessionLog,
    say: (text: string) => pump.submit({ kind: 'message', text }),
    close: async () => {
      await detach.detach();
      await built.dispose();
    },
  };
}

const userTexts = (request: WireRequest) =>
  request.messages
    .filter((message) => message.role === 'user')
    .map((message) =>
      typeof message.content === 'string' ? message.content : JSON.stringify(message.content),
    );

const typesOf = (events: readonly SessionEvent[]) => events.map((event) => event.type);

describe('沒選過的會話與今天一樣', () => {
  it('請求走預設模型、沒有通知、model/start 記著走的路由', async () => {
    const endpoint = await fakeEndpoint([{ text: '一。' }, { text: '二。' }]);
    const run = await assemble(endpoint.baseUrl);
    try {
      await run.say('第一句');
      await run.say('第二句');
      expect(endpoint.requests.map((request) => request.model)).toEqual([A, A]);
      for (const request of endpoint.requests) {
        expect(userTexts(request).join('\n')).not.toContain('[model changed');
      }
      const starts = run.log.events.filter((event) => event.type === 'model/start');
      expect(starts.map((event) => event.data)).toEqual([
        { route: { model: A } },
        { route: { model: A } },
      ]);
      expect(typesOf(run.log.events)).not.toContain('model/selection');
      // 投影：沒選過，next 等於走的。
      expect(modelSelectionView(foldModelSelection(run.log.events))).toEqual({
        lastUsed: { modelId: A },
        next: { modelId: A },
      });
    } finally {
      await run.close();
      await endpoint.close();
    }
  }, 60_000);
});

describe('選了別顆', () => {
  it('下一輪起 request.model 換成選的；附一則 user 角色的通知，逐字照 dsh，只附一次', async () => {
    const endpoint = await fakeEndpoint([{ text: '一。' }, { text: '二。' }, { text: '三。' }]);
    const run = await assemble(endpoint.baseUrl);
    try {
      await run.say('第一句');
      run.host.controller.select({ model: B });
      await run.say('第二句');
      await run.say('第三句');

      expect(endpoint.requests.map((request) => request.model)).toEqual([A, B, B]);
      expect(userTexts(endpoint.requests[0]!).join('\n')).not.toContain('[model changed');
      const second = userTexts(endpoint.requests[1]!).filter((text) =>
        text.includes('[model changed'),
      );
      expect(second).toHaveLength(1);
      expect(second[0]).toContain(NOTICE_A_TO_B);
      // 第三輪的歷史仍帶著那一則（它在 state 裡），但不會再多附一則。
      const third = userTexts(endpoint.requests[2]!).filter((text) =>
        text.includes('[model changed'),
      );
      expect(third).toHaveLength(1);

      const notices = run.log.events.filter(
        (event) =>
          event.type === 'user/message' &&
          event.data.source.kind === 'plugin' &&
          event.data.source.plugin === 'model-selection',
      );
      expect(notices).toHaveLength(1);
      expect(run.log.events.filter((event) => event.type === 'model/selection')).toHaveLength(1);
      expect(
        run.log.events
          .filter((event) => event.type === 'model/start')
          .map((event) => (event.type === 'model/start' ? event.data.route?.model : undefined)),
      ).toEqual([A, B, B]);
      expect(modelSelectionView(foldModelSelection(run.log.events))).toEqual({
        lastUsed: { modelId: B },
        next: { modelId: B },
      });
    } finally {
      await run.close();
      await endpoint.close();
    }
  }, 60_000);

  it('只換強度不附通知；請求帶關推理的寫法', async () => {
    const endpoint = await fakeEndpoint([{ text: '一。' }, { text: '二。' }]);
    const run = await assemble(endpoint.baseUrl);
    try {
      await run.say('第一句');
      run.host.controller.select({ model: A, effort: 'off' });
      await run.say('第二句');
      expect(endpoint.requests.map((request) => request.model)).toEqual([A, A]);
      expect(userTexts(endpoint.requests[1]!).join('\n')).not.toContain('[model changed');
      expect(JSON.stringify(endpoint.requests[0]!.body)).not.toContain('enable_thinking');
      expect(JSON.stringify(endpoint.requests[1]!.body)).toContain('"enable_thinking":false');
      expect(
        run.log.events
          .filter((event) => event.type === 'model/start')
          .map((event) => (event.type === 'model/start' ? event.data.route : undefined)),
      ).toEqual([{ model: A }, { model: A, effort: 'off' }]);
    } finally {
      await run.close();
      await endpoint.close();
    }
  }, 60_000);

  it('一步跑到一半才選：這一步不換，下一步起換並附通知', async () => {
    const hook: { select?: () => void } = {};
    const endpoint = await fakeEndpoint(
      [{ call: { id: 'call_1', name: 'echo', arguments: '{"text":"嗨"}' } }, { text: '完。' }],
      (count) => {
        if (count === 1) hook.select?.();
      },
    );
    const run = await assemble(endpoint.baseUrl);
    hook.select = () => run.host.controller.select({ model: B });
    try {
      await run.say('第一句');
      expect(endpoint.requests.map((request) => request.model)).toEqual([A, B]);
      const second = userTexts(endpoint.requests[1]!).filter((text) =>
        text.includes('[model changed'),
      );
      expect(second).toHaveLength(1);
    } finally {
      await run.close();
      await endpoint.close();
    }
  }, 60_000);
});

describe('兩條 thread 各選各的', () => {
  it('一條選了 B，另一條仍走 A', async () => {
    const endpoint = await fakeEndpoint([{ text: '甲。' }, { text: '乙。' }]);
    const one = await assemble(endpoint.baseUrl);
    const two = await assemble(endpoint.baseUrl);
    try {
      one.host.controller.select({ model: B });
      await one.say('甲');
      await two.say('乙');
      expect(endpoint.requests.map((request) => request.model)).toEqual([B, A]);
    } finally {
      await one.close();
      await two.close();
      await endpoint.close();
    }
  }, 60_000);
});

describe('續接保留選擇', () => {
  it('同一份日誌接上新的控制器：選擇與最近走的都從日誌讀回', async () => {
    const endpoint = await fakeEndpoint([{ text: '一。' }]);
    const run = await assemble(endpoint.baseUrl);
    try {
      run.host.controller.select({ model: B, effort: 'default' });
      await run.say('第一句');
      const events = [...run.log.events];

      const resumed = await assemble(endpoint.baseUrl);
      try {
        for (const event of events) {
          if (event.type === 'model/selection' || event.type === 'model/start') {
            resumed.log.append(event.type, event.data as never);
          }
        }
        expect(resumed.host.controller.next()).toEqual({ model: B });
        expect(resumed.host.controller.state().lastUsed).toEqual({ model: B });
      } finally {
        await resumed.close();
      }
    } finally {
      await run.close();
      await endpoint.close();
    }
  }, 60_000);
});

describe('型錄與驗證（model.select 用）', () => {
  it('型錄、預設與可選強度；不在型錄或沒宣告的強度一律拒', async () => {
    const endpoint = await fakeEndpoint([]);
    const run = await assemble(endpoint.baseUrl);
    try {
      const catalog = run.host.catalog();
      expect(catalog.default).toEqual({ modelId: A });
      expect(catalog.models.map((model) => model.id)).toEqual([A, B]);
      expect(catalog.models[0]?.reasoning?.efforts.map((effort) => effort.id)).toEqual([
        'default',
        'off',
      ]);
      expect(catalog.models[1]?.reasoning).toBeUndefined();

      expect(run.host.validate({ modelId: A, reasoningEffort: 'off' })).toEqual({
        model: A,
        effort: 'off',
      });
      expect(run.host.validate({ modelId: A, reasoningEffort: 'default' })).toEqual({ model: A });
      expect(run.host.validate({ modelId: 'nope' })).toEqual({
        code: 'model_unavailable',
        modelId: 'nope',
      });
      expect(run.host.validate({ modelId: B, reasoningEffort: 'off' })).toMatchObject({
        code: 'model_unavailable',
      });
      expect(run.host.validate({ modelId: A, reasoningEffort: 'high' })).toMatchObject({
        code: 'model_unavailable',
      });
    } finally {
      await run.close();
      await endpoint.close();
    }
  }, 60_000);
});
