/**
 * GENERATED by `apps/harness/src/gen-known-event-types.ts` — 不要手改；執行
 * `pnpm --filter @nexus/harness run gen-known-event-types` 重新生成（`apps/harness/src/known-event-types.test.ts` 驗它沒過期）。
 *
 * 這個 repo 的套件寫得出來的每一種會話事件：核心的 `SessionEventMap` 加上各套件用 `declare module
 * '@nexus/core'` 補的。日誌讀方碰到表外的種類、又沒標 `ignorable` 就拒絕重建（#507，`session-log.ts` 的
 * `isUnreadableSessionEvent`）。比這個 repo 更新的程式寫的種類、或別的東西寫的，自然在表外。
 *
 * @module
 */

/** 這一版認得的事件種類。 */
export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = new Set([
  'approval/asked',
  'approval/decided',
  'approval/policy',
  'assistant/attempt',
  'assistant/message',
  'command/done',
  'command/run',
  'compaction/summary',
  'context/measure',
  'deliverables/presented',
  'feedback/message-delete',
  'feedback/message-put',
  'feedback/record',
  'goal/change',
  'image/offload',
  'inbox/spliced',
  'interrupt/raised',
  'interrupt/system-answered',
  'llm/retry',
  'llm/retry-started',
  'model/end',
  'model/selection',
  'model/start',
  'model/usage',
  'permission/preset',
  'plan/mode',
  'request/header',
  'request/system',
  'sandbox/mode',
  'session/end-seed',
  'session/resumed',
  'session/title',
  'session/title-llm-request',
  'subagent/catalog',
  'subagent/model-selection-policy',
  'todo/write',
  'tool/call',
  'tool/result',
  'turn/end',
  'turn/failed',
  'turn/start',
  'user/message',
  'workspace/changes',
]);
