/**
 * 每會話模型選擇的**機制**：下一步起用哪一顆模型與推理強度、怎麼換、換了怎麼告訴模型
 * （[#723](https://github.com/DemianLi/nexus-agent/issues/723)）。
 *
 * 照 dsh `installModelSelection`（`packages/core/agent/src/model-selection.ts:81-143`，`5badb15`）。三件事，對到它的三個監聽：
 *
 * 1. **每一步開頭快照選擇，這一步的請求用快照**（dsh `system-prompt/assemble` 記下 `assembled`，`agent/request` 套用它）。選擇從
 *    **下一步**生效，跑著的那一步不換。我們的快照在 {@link ModelSelectionController.assembleStep}（`beforeModel` 那一側，跟換模型通知同一刻），
 *    套用在 {@link createModelSwapMiddleware} 的 `wrapModelCall`（把 `request.model` 換成選中那顆的實例）。
 * 2. **provider／model 變了，下一個請求附一則 user 角色的通知；只換強度不附**（dsh `agent/pre-step`，`sameRoute` 只比 provider 與 model）。
 *    比的是「**最近一次請求實際走的路由**」（`model/start.route`，dsh 的 `requestHeader().config`）對這一步選定的，不是對上一次的選擇。
 *    通知文字逐字照 dsh（{@link modelSwitchNoticeText}），來源標成非 user（#662：不把重複工具提醒的鏈清零）。
 * 3. **沒有東西可換的請求不附通知**：第一次請求沒有「最近一次」，所以不附。
 *
 * ## 與 dsh 的差異（登記）
 *
 * - **通知掛在重複提醒那顆 `beforeModel` 上，不另開一個節點。** dsh 的 `agent/pre-step` 是迴圈裡的一個 waterfall，免費；我們的迴圈是基座的圖，
 *   每一顆 `beforeModel` 是圖裡的一個節點，**每一步多一個 super-step**（`repeat-reminder.ts` 實測過）。重複提醒本來就掛了一顆（出廠開著），
 *   所以通知借它的節點（{@link StepNoticeSource}）。重複提醒被關掉時才另掛一顆（`createStepNoticeMiddleware`，付那一格）。
 * - **通知附加失敗不會重複附。** dsh 寫「失敗在 header 寫入之前，下一個請求再附一次」；我們的通知先進 state、也進日誌，之後的請求都看得到，
 *   所以下一步要擋掉「已經附過、還沒有請求用過」的那種（{@link pendingNotice}），不然會附兩則。
 * - **沒有 `provider`。** 見 `model-route.ts`。
 * - **`beforeModel` 被跳過的那一步（`afterAgent` 的 `jumpTo: 'model'`）沒有通知。** 那一步照樣換模型（`wrapModelCall` 沒有跳過），
 *   通知則要等下一個走過 `beforeModel` 的步；但那時「最近一次請求走的」已經是新的那顆，比不出差別，所以那一次**永遠不附**。
 *   窄：要在插話收尾的那個縫上剛好換模型。
 *
 * @module
 */

import { HumanMessage } from '@langchain/core/messages';
import type { BaseChatModel } from '@langchain/core/language_models/chat_models';
import { createMiddleware } from 'langchain';

import type { AgentMiddleware } from './base-types.js';
import { toLoggedMessage, fromLoggedMessage } from './logged-message.js';
import { messageSourceOf, sourceKwargs } from './message-source.js';
import { normalizeRoute, sameModel } from './model-route.js';
import type { ModelRoute } from './model-route.js';
import type { SessionLog, SessionEvent } from './session-log.js';

/** 通知那則 `user/message` 的來源 plugin 名，也是 `nexus_source.kind`。 */
export const MODEL_SELECTION_NOTICE_KIND = 'model-selection';

/** 換模型的 middleware 名字。 */
export const MODEL_SELECTION_MIDDLEWARE_NAME = 'nexusModelSelection';

/**
 * 通知文字，**逐字**照 dsh（`model-selection.ts:53`）。
 *
 * @param from - 上一次請求走的模型 id。
 * @param to - 這一步選定的模型 id。
 */
export function modelSwitchNoticeText(from: string, to: string): string {
  return `[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`;
}

/** 日誌上最後一次請求實際走的路由；一顆都沒有（或舊日誌）是 `undefined`。 */
export function recordedRoute(events: readonly SessionEvent[]): ModelRoute | undefined {
  for (let at = events.length - 1; at >= 0; at -= 1) {
    const event = events[at];
    if (event?.type === 'model/start' && event.data.route !== undefined) {
      return normalizeRoute(event.data.route);
    }
  }
  return undefined;
}

/** 日誌上最後一次使用者的選擇；沒選過是 `undefined`。 */
export function recordedSelection(events: readonly SessionEvent[]): ModelRoute | undefined {
  for (let at = events.length - 1; at >= 0; at -= 1) {
    const event = events[at];
    if (event?.type === 'model/selection') {
      return normalizeRoute({
        model: event.data.modelId,
        ...(event.data.reasoningEffort !== undefined && { effort: event.data.reasoningEffort }),
      });
    }
  }
  return undefined;
}

/**
 * 已經附了這個通知、而且還沒有請求用過它：從尾端往前找，碰到 `model/start` 就停（那之前的通知已經被一次請求看過了）。
 */
export function pendingNotice(events: readonly SessionEvent[], to: string): boolean {
  for (let at = events.length - 1; at >= 0; at -= 1) {
    const event = events[at];
    if (event === undefined) continue;
    if (event.type === 'model/start') return false;
    if (event.type !== 'user/message') continue;
    if (
      event.data.source.kind !== 'plugin' ||
      event.data.source.plugin !== MODEL_SELECTION_NOTICE_KIND
    ) {
      continue;
    }
    const source = messageSourceOf(fromLoggedMessage(event.data.message));
    if (source?.kind === MODEL_SELECTION_NOTICE_KIND && source.to === to) return true;
  }
  return false;
}

/** 組裝點交給控制器的東西：部署預設，與「這條路由的模型實例」。 */
export interface ModelSelectionOptions {
  /** 部署預設的路由（沒選過、日誌上也沒有路由的會話用它）。 */
  readonly defaultRoute: ModelRoute;
  /**
   * 這條路由要用的模型實例（同一條路由回同一個實例，由呼叫端快取）。**回 `undefined` ＝ 沿用 `request.model` 原本那顆**
   * （預設那顆；它在組裝時建好，不為它另建一個實例，也就是沒選過的會話送出去的請求與今天逐欄一致）。
   */
  readonly instanceFor: (route: ModelRoute) => BaseChatModel | undefined;
}

/**
 * 一條會話（root）的模型選擇。**狀態都在日誌上**（`model/selection` 與 `model/start.route`），這個物件只多一格每一步的快照。
 *
 * 一條 thread 一個：serve 每條 thread 各組裝一次，CLI 一個 REPL 一個。
 */
export class ModelSelectionController {
  readonly #options: ModelSelectionOptions;
  #log: SessionLog | undefined;
  #assembled: ModelRoute | undefined;

  constructor(options: ModelSelectionOptions) {
    this.#options = options;
  }

  /** 部署預設。 */
  get defaultRoute(): ModelRoute {
    return normalizeRoute(this.#options.defaultRoute);
  }

  /** 接上 root 的日誌（`registry.sessions.join` 時）。重複接同一份無妨。 */
  attach(log: SessionLog): void {
    this.#log = log;
  }

  /** 日誌上的現況：最近一次請求走的、與使用者最後一次選的（沒有就是 `undefined`）。 */
  state(): { lastUsed: ModelRoute | undefined; selected: ModelRoute | undefined } {
    const events = this.#log?.events ?? [];
    return { lastUsed: recordedRoute(events), selected: recordedSelection(events) };
  }

  /**
   * **下一步會用的路由**：使用者最後選的 → 最近一次請求走的 → 部署預設。
   *
   * 順序照 dsh（`agent.ts:295-298`）：沒選過的會話先沿用日誌裡最後一個請求的路由，再沒有才讀部署預設。選擇不會被「消耗」：選了
   * 之後它一直是這條會話的選擇，直到下一次選；所以不能拿「日誌上哪一顆比較新」判斷（一步開頭快照之後、請求之前才選的，
   * `model/selection` 會落在舊路由的 `model/start` 前面）。
   */
  next(): ModelRoute {
    const { lastUsed, selected } = this.state();
    return selected ?? lastUsed ?? this.defaultRoute;
  }

  /**
   * 記下使用者的選擇。**不驗證**——型錄與強度的檢查在呼叫端（它才有型錄），驗過才能呼叫這裡。
   *
   * @throws 還沒接上日誌：選擇無處可記。
   */
  select(route: ModelRoute): void {
    if (this.#log === undefined) throw new Error('model-selection：還沒接上會話日誌，選擇無處可記');
    const normalized = normalizeRoute(route);
    this.#log.append('model/selection', {
      modelId: normalized.model,
      ...(normalized.effort !== undefined && { reasoningEffort: normalized.effort }),
    });
  }

  /** 一步開頭快照下一步的路由（`beforeModel` 那一側）。同一步的 {@link takeStepRoute} 會用它。 */
  assembleStep(): ModelRoute {
    this.#assembled = this.next();
    return this.#assembled;
  }

  /**
   * 這一步的請求用哪條路由，並清掉快照。沒有快照（`beforeModel` 沒跑到、或重複提醒與通知節點都沒掛）就現算。
   * **清掉是承重的**：留著會讓 `beforeModel` 被跳過的下一步用上一步的舊快照。
   */
  takeStepRoute(): ModelRoute {
    const route = this.#assembled ?? this.next();
    this.#assembled = undefined;
    return route;
  }

  /** 這條路由要用的實例；`undefined` ＝ 沿用 `request.model`。 */
  instanceFor(route: ModelRoute): BaseChatModel | undefined {
    return this.#options.instanceFor(normalizeRoute(route));
  }

  /**
   * 這一步要附的換模型通知。`found` 要是 root 的日誌；只有「最近一次請求走的」跟這一步選定的**模型**不同才附。
   */
  noticeFor(log: SessionLog): readonly HumanMessage[] {
    const route = this.assembleStep();
    const previous = recordedRoute(log.events);
    if (previous === undefined || sameModel(previous, route)) return [];
    if (pendingNotice(log.events, route.model)) return [];
    const message = new HumanMessage({
      content: [{ type: 'text', text: modelSwitchNoticeText(previous.model, route.model) }],
      additional_kwargs: sourceKwargs({
        kind: MODEL_SELECTION_NOTICE_KIND,
        form: 'notice',
        from: previous.model,
        to: route.model,
      }),
    });
    try {
      log.append('user/message', {
        message: toLoggedMessage(message),
        source: { kind: 'plugin', plugin: MODEL_SELECTION_NOTICE_KIND },
      });
    } catch {
      // 記不進去通知照樣送出（同重複提醒）。
    }
    return [message];
  }
}

/**
 * 換模型的 middleware：每一步把 `request.model` 換成這一步選定的那顆。**只折進 root**（`fold.ts` 的 `rootOnly`）。
 *
 * 排在摘要器、起訖與用量記錄器的**外面**：它們看到的 `request.model` 就是選中的那顆（摘要用它生、`model/start.route` 讀它的標籤、
 * 估算的錨按它的名字認）。選中的就是預設那顆時什麼都不換，請求逐欄與沒有這顆 middleware 時一樣。
 *
 * @param controller - 這條會話的控制器。
 */
export function createModelSwapMiddleware(controller: ModelSelectionController): AgentMiddleware {
  return createMiddleware({
    name: MODEL_SELECTION_MIDDLEWARE_NAME,
    wrapModelCall: (request, handler) => {
      const route = controller.takeStepRoute();
      const instance = controller.instanceFor(route);
      // 預設那顆（`instanceFor` 回 `undefined`）不換：沒選過的會話送出去的請求與沒有這顆 middleware 時逐欄一樣。
      if (instance === undefined || instance === request.model) return handler(request);
      return handler({ ...request, model: instance });
    },
  }) as unknown as AgentMiddleware;
}
